site_name: SuperCloud Docs
site_url: https://supercloud.mit.edu
nav:
    - Home: index.md
    - Requesting an Account: requesting-account.md
    - Getting Started: getting-started.md
    - Systems and Software: systems-and-software.md
    - Acknowledging Us: acknowledging-us.md
    - Using the System:
      - Files and Data:
        - Transferring Files: using-the-system/files-and-data/transferring-files.md
        - Shared Groups: using-the-system/files-and-data/shared-groups.md
      - Software and Package Management: using-the-system/software-packages.md
      - Monintoring System and Job Status: using-the-system/monitoring-system-and-jobs.md
      - Submitting Jobs:
        - Submitting Jobs: using-the-system/submitting-jobs/submitting-jobs.md
        - Job Array Triples: using-the-system/submitting-jobs/job-array-triples.md
      - Best Practices:
        - Best Practices for using the Filesystem: using-the-system/best-practices/filesystem.md
        - Optimizing your GPU Jobs: using-the-system/best-practices/gpu-jobs.md
      - Web Portal: using-the-system/web-portal.md
      - Databases: using-the-system/databases.md
      - Jupyter Notebooks: using-the-system/jupyter-notebooks.md
    - Additional Resources: 
      - Frequently Asked Questions: faqs.md
      - Getting Help: getting-help.md
      - Glossary: glossary.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: 
