site_name: SuperCloud Docs
site_url: https://supercloud.mit.edu
nav:
  - Home: index.md
  - Requesting an Account: requesting-account.md
  - Getting Started: getting-started.md
  - Systems and Software: systems-and-software.md
  - Acknowledging Us: acknowledging-us.md
  - Using the System: 
    - Files and Data:
      - Transferring Files: using-the-system/files-and-data/transferring-files.md
      - Shared Groups: using-the-system/files-and-data/shared-groups.md
    - Installing Software:
      - Software and Package Management: using-the-system/software-packages.md  
    - Submitting Jobs:
      - Monitoring System and Job Status: using-the-system/monitoring-system-and-jobs.md
      - Submitting Jobs: using-the-system/submitting-jobs/submitting-jobs.md
      - Job Array Triples: using-the-system/submitting-jobs/job-array-triples.md
    - Best Practices:
      - Best Practices for using the Filesystem: using-the-system/best-practices/filesystem.md
      - Optimizing your GPU Jobs: using-the-system/best-practices/gpu-jobs.md
    - Web Portal:
      - Logging In: using-the-system/web-portal.md
      - Databases: using-the-system/databases.md
      - Jupyter Notebooks: using-the-system/jupyter-notebooks.md
  - Frequently Asked Questions: faqs.md
  - Getting Help: getting-help.md
  - Glossary: glossary.md
#theme: readthedocs
theme: 
  name: material
  features:
    - content.code.copy
markdown_extensions:
    - toc:
        permalink: 
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
